### ISSUE TITLE
Not able to create chain tasks in parallel tasks

### ISSUE THREAD

**Issue by baloda** [ovh/celery-director#40]
I am trying to create a below-defined workflow and it is giving error 
```
p.TEST:
  tasks:
    - TEST_1
    - TEST_2
    - WORKERS:
        type: group
        tasks:
          - TEST_3
          - TEST3_WORKERS:
            type: chain
            tasks:
              - TEST_6
              - TEST_7
          - TEST_4
          - TEST_5
    - TEST_8
```

Error:
```
signature = cel.tasks.get(task_name).subtask(
TypeError: unhashable type: dict
```
