### ISSUE TITLE
Workflow Hooks

### ISSUE THREAD

**Issue by anthonyolea** [ovh/celery-director#60]
Handle hooks in the `workflows.yml` file.
Example:
```
demo.EXAMPLE:
  tasks:
    - EXTRACT_TASK
    - TRANSFORM_TASK
    - LOAD_TASK
  hooks:
     success: SUCCESS_TASK
     failure: FAILURE_TASK
```
